GET http://localhost:3333/users/all

###

GET http://localhost:3333/auth/all

###

GET http://localhost:3333/users/c84df423-5d7c-4dc1-9fb8-1023f23d60d7

###

POST http://localhost:3333/users/register
Content-Type: application/json


{
    "name": "jose",
    "lastname": "gama",
    "email": "ronalalmeida20022003@gmail.com",
    "password": "minhaSenha"
}